<a href="https://colab.research.google.com/github/SaranyaKesavan/Python-DataScience/blob/master/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numerical Python (NumPy)**

In [0]:
import numpy as np

# Creating Arrays

In [0]:
# create a list and convert it to numpy array
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [0]:
# or just pass the list directly
y = np.array([4,5,6])
y

array([4, 5, 6])

In [0]:
# Pass a list of lists to create multidimensional array
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
# use shape method to find the dimensions of the array (rows,columns)
m.shape

(2, 3)

In [0]:
# use arange method to return evenly spaced values within a given interval

n = np.arange(0, 30, 2)
# starts at 0 count up by 2, stops before 30
print(n)
n.shape

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


(15,)

In [0]:
# reshape returns an array with the same data with a new shape

n = n.reshape(3,5) #reshape array to be 3X5 [rows X cols = total ele]
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [0]:
#reshape array to be 3X5 [rows X cols = total ele]
n.reshape(4,4)

ValueError: ignored

In [0]:
#linspace returns evenly spaced numbers over a specified interval

o = np.linspace(0, 4, 9)
#return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [0]:
#resize changes the shape and size of array in-place

o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

# reshape Vs resize



In [0]:
arrayA = np.arange(8)
arrayA

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
np.reshape(arrayA,(2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:
#if rows X cols != tot ele throws valuerror
np.reshape(arrayA,(3,4))

ValueError: ignored

In [0]:
# order = C ;to read or write data in C-like index order, or in simple words, in the order of row
# order = F ;to read or write data in Fortan-like index order, or let’s say, in the order of column
np.reshape(arrayA,(2,4),order = 'C')
np.reshape(arrayA,(2,4),order = 'F')



array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [0]:
#reshape does -->> shallow copy shared memory to know run python visualizer
#resize does -->> deep copy nt shared memory
import numpy as np
arrayA = np.arange(8)
rsArray = np.reshape(arrayA,(2,4))
arrayA[5] = 100
print(arrayA)
print(rsArray)

arrayB = np.arange(8)
arrayC = np.resize(arrayB,(2,4))
arrayB[5] = 100
print(arrayB)
print(arrayC)






[  0   1   2   3   4 100   6   7]
[[  0   1   2   3]
 [  4 100   6   7]]
[  0   1   2   3   4 100   6   7]
[[0 1 2 3]
 [4 5 6 7]]


In [0]:
"""resize:::
    --> no order parameter default is C order
    --> if rows X cols != tot ele ==>> 
            -- no error
            -- forces to resize
                new array has more rows, 
                it will repeat the data in the original array 
                but not raise the error.
"""
arrayD = np.arange(8)
arrayE = np.resize(arrayD,(2,4))
arrayE

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:
arrayF = np.resize(arrayD,(3,4))
arrayF #no error forces resize

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3]])

# -- X --

In [0]:
#ones returns new array of given shape and type filled with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
#zeros returns a new array of given shape and type filled with zeros
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
#eye returns a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(4) #square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
#diag extracts a diagonal or constructs a diagonal array
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [0]:
y

array([4, 5, 6])

In [0]:
np.resize(y,(3,1))

array([[4],
       [5],
       [6]])

In [0]:

arrayE

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [0]:

y

array([4, 5, 6])

In [0]:
# for one dimensional array returns diagonal matrix
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [0]:
# for multidimensinal array returns the main diagonal
np.diag(arrayE)

array([0, 5])

In [0]:
#here it treats each list as a single element of type object 
# cuz col length of all row is not same
arr = [[1, 21, 30,77],  
                [63 ,434, 3, 88],  
                [54, 54, 56, 99,100]]
np.diag(arr)

array([[list([1, 21, 30, 77]), 0, 0],
       [0, list([63, 434, 3, 88]), 0],
       [0, 0, list([54, 54, 56, 99, 100])]], dtype=object)

In [0]:
 
# matrix creation by array input 
eg = np.matrix([[1, 21, 30,77],  
                [63 ,434, 3, 88],  
                [54, 54, 56, 99,100]]) 
print("Main Diagnol elements : \n", np.diag(eg), "\n") 
  
print("Diagnol above main diagnol : \n", np.diag(eg, 1), "\n") 
  
print("Diagnol below main diagnol : \n", np.diag(eg, -1)) 

Main Diagnol elements : 
 [list([1, 21, 30, 77])] 

Diagnol above main diagnol : 
 [list([63, 434, 3, 88])] 

Diagnol below main diagnol : 
 []


In [0]:
# creating an array using repeating list (or see np.tile() check geeksforgeeks)
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
#np.tile(array, repetation)
za = np.array([1,2,3,4,5]) # single dimension array
np.tile(za,3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [0]:
#using multi dimension array
zb = np.array([[1,2,3],[4,5,6]])
np.tile(zb,2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [0]:
np.tile(zb,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [0]:
np.tile(zb,(2,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [0]:
np.tile(zb,(1,2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [0]:
np.tile(za,(2,3))

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [0]:
#repeat elements of an array using "repeat" r

#repeats each ele n no of times
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [0]:
np.repeat([[1.2],[3,4]],2)

array([list([1.2]), list([1.2]), list([3, 4]), list([3, 4])], dtype=object)

In [0]:
np.repeat([[1.2],[3,4]],(2,3))


array([list([1.2]), list([1.2]), list([3, 4]), list([3, 4]), list([3, 4])],
      dtype=object)

# **Combining Arrays**

In [0]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [0]:
# use vstack to stack arrays in sequence vertically (row wise)
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [0]:
np.vstack([p, p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
np.vstack([p, [3,3,3]])

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3]])

In [0]:
np.vstack([p, [1,2]])

ValueError: ignored

In [0]:
#use hstacck to stack arrays in sequence horizontally (column wise)
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [0]:
np.hstack([p, [3,3,4]])

ValueError: ignored

In [0]:
np.hstack([p, [[3,4,5],[6,7,8]]])

array([[1, 1, 1, 3, 4, 5],
       [1, 1, 1, 6, 7, 8]])

# **operations**

## use  +, - * ,/ ,** to perform element wise addition, subtraction, multiplication, division and power

In [0]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [0]:
print(x + y) #element wise addition

[5 7 9]


In [0]:
print(x - y) #element wise subtaction

[-3 -3 -3]


In [0]:
print(x * y) #element wise multiplication

[ 4 10 18]


In [0]:
print(x / y) #element wise division

[0.25 0.4  0.5 ]


In [0]:
print(x ** y) # element wise power

[  1  32 729]


In [0]:
print(x ** 2) # element wise power

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$




In [0]:
# dot product
x.dot(y)  # 1*4 + 2*5 + 3*6

32

In [0]:
z = np.array([y, y**2])
print(z)
print(len(z)) # no of rows of array

[[ 4  5  6]
 [16 25 36]]
2


# transposing array -- reverses dimensions of array r-->c ; c-->r

In [0]:
z = np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [0]:
# shape of array bfr transpose
z.shape

(2, 3)

In [0]:
# use .T to transpose the array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [0]:
#shape after transpose
z.T.shape

(3, 2)

In [0]:
# .dtype ==>> to see data type of ele in the array
z.dtype

dtype('int64')

In [0]:
# .astype ==>> casts / converts to a specific type
z = z.astype('f')
z.dtype

dtype('float32')

# math functions

In [0]:
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [0]:
a.sum() # sum of array

3

In [0]:
a.max() # max ele in the array

5

In [0]:
a.min() # min ele in the array

-4

In [0]:
a.mean() # avg of ele in the array

0.6

# for SD formula and process checkout
# https://www.mathsisfun.com/data/standard-deviation-formulas.html

In [0]:

a.std() # gives standard deviation of the gn array

3.2619012860600183

# argmax() and argmin()  ==>> returns the index of max and min values in the array

In [0]:
a.argmin() # returns the index of -4 i.e., 0

0

In [0]:
a.argmax() # returns the index of 5 i.e., 4

4

# indexing  / Slicing

In [0]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [0]:
# simiklar to list and usual array indexing with  -ve indexing
s[0] , s[4], s[-1]

(0, 16, 144)

In [0]:
# [start : stop]
# default ==>> [:] -- includes all i.e., begining and end of array
s[1:6]

array([ 1,  4,  9, 16, 25])

In [0]:
# allows -ve indexing
s[-4 : ]

array([ 81, 100, 121, 144])

In [0]:
s[-8 : -4]

array([25, 36, 49, 64])

In [0]:
# [start : stop : stepsize]
# stepsize +ve ==>counts forward
# -ve ==> counts backward
s[-5 : : -2]

array([64, 36, 16,  4,  0])

In [0]:
s[-5 :: 2]

array([ 64, 100, 144])

# indexing / slicing for multi dimensional array

In [0]:
r = np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
# use bracket notation to slice array[row, column] --> similar to matrix
r[2,2]

14

In [0]:
# use  ':' to select range of rows or columns
r[3, 3:6]

array([21, 22, 23])

In [0]:
# selects all the rows upto (and not including) row 2 and
# all columns up to (and not including) the last column
r[ : 2 , : -1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [0]:
# selects nly last row and all ele of last row with skip count 2
r[-1 , ::2]

array([30, 32, 34])

# conditional indexing

In [0]:
# gives all ele in the array 'r' which are > 30
r[r > 30]

array([31, 32, 33, 34, 35])

In [0]:
r[r >20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [0]:
# assings all the values in the array which are grt than 30 to 30 
print(r)
r[r > 30 ] = 30
r

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copying Data
# ***NOTE: Be careful with copying and modifying arrays in NumPy***

In [0]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
# r2 is a slice of r
r2 = r[:3 , :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [0]:
# set the sliced values to zero in r2
# use [:] to select all ele of the array
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
# modifying r2 reflected in r ==> shallow copy shares same memory
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
# to avoid condition in cell 90 use .copy()

# .copy() ==>> does deep copy and changes won't affect the original array

r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [0]:
# this time r will not be changed
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating over arrays

In [0]:
# create a new 4 X 3 array of random numbers 0-9
test = np.random.randint(0, 10, (4,3))
test

array([[9, 3, 7],
       [0, 6, 0],
       [9, 6, 3],
       [1, 2, 9]])

In [0]:
# iterate by row
for row in test:
    print(row)

[9 3 7]
[0 6 0]
[9 6 3]
[1 2 9]


In [0]:
# iterate by index
for i in range(len(test)): # len(array) gives row count
    print(test[i])

[9 3 7]
[0 6 0]
[9 6 3]
[1 2 9]


In [0]:
# iterate by row and index
for i, row in enumerate(test):
    print('row ' , i, ' is ', row)

row  0  is  [9 3 7]
row  1  is  [0 6 0]
row  2  is  [9 6 3]
row  3  is  [1 2 9]


In [0]:
# use zip to iterate over multiple iterables
test2 = test ** 2
test2

array([[81,  9, 49],
       [ 0, 36,  0],
       [81, 36,  9],
       [ 1,  4, 81]])

In [0]:
for i, j  in zip(test,test2):
    print(i,' + ' ,j ,' = ', i+j)

[9 3 7]  +  [81  9 49]  =  [90 12 56]
[0 6 0]  +  [ 0 36  0]  =  [ 0 42  0]
[9 6 3]  +  [81 36  9]  =  [90 42 12]
[1 2 9]  +  [ 1  4 81]  =  [ 2  6 90]
